- lzero/mcts/ctree/ctree_efficientzero/ez_tree.pxd
- lzero/mcts/ctree/ctree_efficientzero/ez_tree.pyx
- lzero/mcts/ctree/ctree_efficientzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_efficientzero/lib/cnode.h
- lzero/mcts/ctree/ctree_muzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_muzero/lib/cnode.h
- lzero/mcts/ctree/ctree_muzero/mz_tree.pxd
- lzero/mcts/ctree/ctree_muzero/mz_tree.pyx
- lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.pxd
- lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.pyx
- lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.h
- lzero/mcts/ptree/ptree_ez.py
- lzero/mcts/ptree/ptree_mz.py
- lzero/mcts/ptree/ptree_sez.py
- lzero/mcts/tree_search/mcts_ctree.py
- lzero/mcts/tree_search/mcts_ctree_sampled.py
- lzero/mcts/tree_search/mcts_ptree.py
- lzero/mcts/tree_search/mcts_ptree_sampled.py
- lzero/mcts/utils.py
polish variable names and annotations in tree_search and ptree/ctree
> polish(pu): polish variable names and annotations in tree_search and ptree/ctree

- lzero/entry/train_alphazero.py
- lzero/entry/train_muzero.py
- lzero/entry/train_muzero_with_gym_env.py
- lzero/mcts/tree_search/mcts_ctree.py
- lzero/policy/alphazero.py
- lzero/policy/efficientzero.py
- lzero/policy/muzero.py
- lzero/policy/sampled_efficientzero.py
utilize model_update_ratio to control update_per_collect automatically
> polish(pu): utilize model_update_ratio to control update_per_collect automatically

- README.md
- README.zh.md
add 3 papers about mcts, polish LightZero intro
> feature(pu): add 3 papers about mcts, polish LightZero intro

- lzero/mcts/tests/atari_efficientzero_config_test.py
- lzero/mcts/tests/tictactoe_muzero_bot_mode_config_test.py
fix(pu): fix test_game_segment.py
> fix(pu): fix test_game_segment.py

- README.md
> fix(elto): typo in README.md

- docs/source/tutorials/algos/customize_algos.md
- docs/source/tutorials/algos/customize_algos_zh.md
- docs/source/tutorials/envs/customize_envs.md
- docs/source/tutorials/envs/customize_envs_zh.md
add four new tutorial docs about customize envs and algorithms in LightZero.
Proofread the formatting of the Chinese and English text and removed unnecessary indentation.
> polish(xcy): update env and algo tutorial doc

- README.md
Added a 'back to top' button in readme to enhance navigation.
> polish(prajjwalyd): added a back to top button in readme.md

- README.zh.md
added back to top in README.zh.md.
Verified the translation in Chinese.
> polish(prajjwalyd): add a back to top button in README.zh.md

- CONTRIBUTING.md
Hey there!
First, if you are reading this, you are amazing! 
I'm Armaan and actively taking part in Hacktoberfest and HackSquad, I was contributing to various repos recently and found out this repo (had a lot of contributions.
As always, I jumped and tried to find out "CONTRIBUTING.md" which all the beginners find first to start contributing but unlike other amazing repos, I couldn't find any, "CONTRIBUTING.md" contains a set of guidelines and steps on how to contribute to the project!
This change (separate file on steps and guidelines) will help increase contributors to contribute even more especially beginners, and to make it fun, emojified and engaging for users!
Who doesn't like fun? : D
So, I went ahead and made a separate "CONTRIBUTING.md" file with steps and guidelines, I hope this …
> feature(armaan): added CONTRIBUTING.md

- CODE_OF_CONDUCT.md
Fixed Issue #125 
@puyuan1996 Kindly Review the PR ! let me know If there is any changes !!
> feature(dhote): added CODE_OF_CONDUCT.md

- lzero/mcts/buffer/game_buffer.py
- lzero/policy/gumbel_muzero.py
- lzero/policy/muzero.py
- zoo/board_games/gomoku/config/gomoku_gumbel_muzero_bot_mode_config.py
- zoo/board_games/tictactoe/config/tictactoe_gumbel_muzero_bot_mode_config.py
- zoo/box2d/lunarlander/config/lunarlander_disc_gumbel_muzero_config.py
- zoo/classic_control/cartpole/config/cartpole_gumbel_muzero_config.py
- zoo/classic_control/pendulum/config/pendulum_cont_disc_gumbel_muzero_config.py
-  fix gumbel muzero collector bug, fix gumbel typo
> fix(pu): fix gumbel muzero collector bug, fix gumbel typo

- lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp
- lzero/policy/alphazero.py
- zoo/board_games/gomoku/config/gomoku_alphazero_bot_mode_config.py
- zoo/board_games/gomoku/config/gomoku_alphazero_sp_mode_config.py
- zoo/board_games/gomoku/envs/gomoku_env.py
- zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_config.py
- zoo/board_games/tictactoe/config/tictactoe_alphazero_sp_mode_config.py
- zoo/board_games/tictactoe/envs/tictactoe_env.py
- fix tictactoe and gomoku env to be compatibility with alphazero ctree
> fix(pu): fix tictactoe and gomoku env for alphazero ctree

- lzero/policy/alphazero.py
- zoo/atari/entry/atari_eval.py
- zoo/atari/envs/atari_lightzero_env.py
- zoo/atari/envs/atari_wrappers.py
- zoo/board_games/connect4/config/connect4_alphazero_bot_mode_config.py
- zoo/board_games/connect4/envs/connect4_env.py
- zoo/board_games/connect4/eval/connect4_alphazero_eval.py
- zoo/board_games/connect4/eval/connect4_muzero_eval.py
- zoo/board_games/gomoku/envs/gomoku_env.py
- zoo/board_games/tictactoe/entry/tictactoe_alphazero_eval.py
- zoo/board_games/tictactoe/entry/tictactoe_muzero_eval.py
- zoo/board_games/tictactoe/envs/tictactoe_env.py
- zoo/box2d/lunarlander/entry/lunarlander_eval.py
- zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
- zoo/box2d/lunarlander/envs/lunarlander_env.py
- zoo/box2d/lunarlander/envs/test_lunarlander_env.py
- zoo/classic_control/cartpole/entry/cartpole_eval.py
- zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
- zoo/classic_control/pendulum/entry/pendulum_eval.py
- zoo/classic_control/pendulum/envs/pendulum_lightzero_env.py
- zoo/game_2048/entry/2048_eval.py
- zoo/game_2048/envs/game_2048_env.py
- polish comments and eval_render_config in cartpole, pendulum, lunarlander,  atari, tictactoe, gomoku, connect4, 2048
> polish(pu): refine comments and render_eval configs for various common environments

- lzero/policy/gumbel_muzero.py
add mask action process in gumbel muzero
> fix(lxy): fix completed value inf bug when zero exists in action_mask in gumbel muzero

- lzero/mcts/ctree/ctree_efficientzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_gumbel_muzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_muzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp
- lzero/mcts/ctree/ctree_stochastic_muzero/lib/cnode.cpp
- lzero/mcts/ptree/minimax.py
- lzero/mcts/ptree/ptree_ez.py
- lzero/mcts/ptree/ptree_mz.py
- lzero/mcts/ptree/ptree_sez.py
- lzero/mcts/ptree/ptree_stochastic_mz.py
- lzero/mcts/tree_search/mcts_ctree.py
- lzero/mcts/tree_search/mcts_ctree_sampled.py
- lzero/mcts/tree_search/mcts_ctree_stochastic.py
- lzero/mcts/tree_search/mcts_ptree.py
- lzero/mcts/tree_search/mcts_ptree_sampled.py
- lzero/mcts/tree_search/mcts_ptree_stochastic.py
- Refine the API documentation for files located in the `mcts/ptree`, `mcts/ctree`, and `mcts/tree_search` directories.
> polish(xcy): polish comments in tree search files

- lzero/entry/train_muzero.py
- lzero/entry/utils.py
- lzero/mcts/tests/test_muzero_game_buffer.py
- lzero/model/common.py
- lzero/model/efficientzero_model.py
- lzero/policy/efficientzero.py
- lzero/policy/muzero.py
- zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py
- zoo/atari/config/atari_muzero_multigpu_ddp_config.py
- fix sync_gradients and log in DDP settings
> fix(pu): fix sync_gradients and log in DDP settings

- zoo/board_games/tictactoe/config/tictactoe_efficientzero_bot_mode_config.py
- zoo/board_games/tictactoe/config/tictactoe_efficientzero_sp_mode_config.py
- add efficientzero tictactoe configs
> feature(pu): add efficientzero tictactoe configs

- README.md
- README.zh.md
- add discord and ZeroPal link
> style(pu): add discord and ZeroPal link

- README.md
- README.zh.md
- Add [UniZero](https://arxiv.org/abs/2406.10667) citation and related info
> feature(pu): add unizero citation and related info

- .github/workflows/test.yml
- requirements.txt
- add self-hosted linux(ubuntu) ci runner
> feature(hus): add self-hosted linux(ubuntu) ci runner 

- lzero/model/common.py
- fix(pu): fix DownSample for different obs shape
> fix(pu): fix DownSample for different obs shape

- lzero/model/stochastic_muzero_model_mlp.py
- zoo/classic_control/cartpole/config/cartpole_stochastic_muzero_config.py
- zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
Fixes issues mentioned in #283
> fix(sk): fix stochastic_muzero_model_mlp.py with chance encoder

- requirements.txt
- zoo/classic_control/cartpole/config/cartpole_muzero_config.py
- zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
- zoo/game_2048/envs/game_2048_env.py
- zoo/game_2048/envs/test_game_2048_env.py
- fix reward type bug in 2048
- fix os import bug in cartpole
- modifying the version requirements for gymnasium in the requirements.txt file
> fix(pu): fix reward type bug in 2048, os import bug in cartpole

- docs/source/tutorials/config/config.md
- docs/source/tutorials/config/config_zh.md
- docs/source/tutorials/logs/logs.md
- docs/source/tutorials/logs/logs_zh.md
Polish config_zh.md/config.md, log_zh.md/log.md in tutorials.
> polish(xjy): update configuration and log instructions in tutorials

- lzero/model/common.py
- zoo/jericho/configs/jericho_unizero_config.py
- zoo/jericho/configs/jericho_unizero_ddp_config.py
- zoo/jericho/configs/jericho_unizero_segment_config.py
- zoo/jericho/envs/jericho_env.py
add jericho ddp config, and polish jericho configs (main change: use fixed temperature=0.25)
> feature(pu): add jericho ddp config

- lzero/worker/muzero_evaluator.py
One more tiny timestep fix that escaped our attention 🙂.
Hopefully the last !
> fix(fir): fix timestep

- lzero/policy/scaling_transform.py
Now that we made #389 we can polish the code.
> polish(fir): polish softmax
